// <auto-generated />
namespace Pedido.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class adicionadovaloraoproduto : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adicionadovaloraoproduto));
        
        string IMigrationMetadata.Id
        {
            get { return "201907220020277_adicionado valor ao produto"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
